apiVersion: v1
kind: Service
metadata:
  name: alpine
  labels:
    app: image
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: image
